#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                   : Measured Uncertainty # The title of the book. Will be placed in the left navbar.
author                  : John Moïse  # The author of the book
copyright               : 2023  # Copyright year to be placed in the footer
only_build_toc_files    : true

#######################################################################################
# Execution settings
execute:
  execute_notebooks     : auto
  timeout               : 600


#######################################################################################
# HTML settings
html:
  favicon               : "favicon.ico"
  navbar_number_sections: true
  home_page_in_navbar   : false
  use_repository_button : true
  use_edit_page_button  : false
  use_issues_button     : false

#######################################################################################
# Repository settings
repository:
  url                   : https://github.com/johnmoise/research  # Online location of your book
  branch                : main  

#######################################################################################
# Latex settings
latex:
  latex_documents:
    targetname        : book.tex # Define the name of the latex output file for PDF builds

#######################################################################################
# Bibtex settings
bibtex_bibfiles:
  - references.bib # Add a bibtex file so that we can create citations
